### ISSUE TITLE
Style in head - quotation mark `"` gets encoded to `&quot;`

### ISSUE THREAD

**Issue by BKFlister** [thomasborgen/hypermedia#37]
Hi,
I am trying to add style to head that contains quotation mark `"`
e.g. `content: "i";` becomes `content: &quot;i&quot;;`
What is the correct method to not get the quotation marks encoded?
Can of-course load the style as a separate css-file, but for showing/sending some examples I want a single py-file containing all parts. 

A minimal example:
```python
Style('.log_message { line-height: 1.1; } .log_message::before { content: "i"; display: inline-block; border-radius: 9999px; width: 1.4rem; margin-right: 4px; vertical-align: 2px; font-size: .7rem; color: white; text-align: center; } '),
```
Result:
```html
<style>.log_message { line-height: 1.1; } .log_message::before { content: &quot;i&quot;; display: inline-block; border-radius: 9999px; width: 1.4rem; margin-right: 4px; vertical-align: 2px; font-size: .7rem; color: white; text-align: center; } </style>
```

There is probably a simple solution, I can blame my lack of experience :-)

**Comment by thomasborgen** [comment]
Yeah, This needs the "skip html escaping" functionality. I'll look into it tomorrow. Thanks for another great catch!

**Comment by thomasborgen** [comment]
@BKFlister 
Should work in `5.3.0` without any changes for you.

**Comment by BKFlister** [comment]
Thanks,
The quotation marks is ok now.

But it when adding text with a slash and a zero `\0` e.g. `content: "\0021";` some sort of encoding happens, `content: "1";`
see image:
<img width="204" alt="image" src="https://github.com/user-attachments/assets/99e75325-672b-440b-bdd7-bca902ad8182">

```python
# simplified example
styles = """.error::before { content: "\0021"; background-color: #f54251; }"""
#...
Style(styles),
#...
```

The result in browsers, tested only on Mac
Chrome:
<img width="271" alt="image" src="https://github.com/user-attachments/assets/b360bdb1-cec0-4116-ad39-06dd7e91b1c9">

Firefox:
<img width="270" alt="image" src="https://github.com/user-attachments/assets/1b3709df-7e34-4df1-9ebf-af6d169a3dc0">

Safari:
<img width="272" alt="image" src="https://github.com/user-attachments/assets/6622c0c3-366a-4ebd-a3e2-252bfda483a1">

**Comment by thomasborgen** [comment]
Since python strings are already unicode I don't think you need to escape this. You are telling python to read a unicode character and `\002` just happens to match before `\0021`. `\002` seems to be a control character "start of text" and then you get the `1` as normal text after that.

Anyways, In your editor try to copy paste this emoji: ❗ and see if it works, it worked for me.

**Comment by thomasborgen** [comment]
```python
Style(""".error::before { content: "❗"; background-color: #f54251; }"""),
```

**Comment by BKFlister** [comment]
Using symbols/emoji directly works. 

I use other symbols for small/simple 
E.g. the Warning Sign `\26A0` =  `⚠`
and the slash make the following 2 digits a control character.
Using the emoji directly works.

Thank you.

**Comment by BKFlister** [comment]
Solved
